name: Despliegue Automatico Instancia 3

# El disparador (Trigger)
on:
  pull_request:
    branches: [ main ]
    types: [ closed ] # Se ejecuta cuando el PR se cierra

jobs:
  deploy:
    # Solo corre si el PR se cerró porque se aceptó (Merge)
    if: github.event.pull_request.merged == true
    runs-on: self-hosted  # Esto le dice a GitHub que use el Droplet
    
    steps:
      - name: Descargar codigo del repo
        uses: actions/checkout@v4

      - name: Desplegar Ambiente Desarrollo
        run: |
          cd /opt/app/dev
          docker-compose pull
          docker-compose up -d

      - name: Desplegar Ambiente Produccion
        run: |
          cd /opt/app/prod
          docker-compose pull
          docker-compose up -d